package org.example.exportproback.audit.domain;

public enum AuditEventType {
    USER_REGISTERED,
    COMPANY_CREATED,
    PRODUCT_CREATED,
    COMPLIANCE_CASE_CREATED,
    COMPLIANCE_CASE_STATUS_CHANGED,
    DOCUMENT_UPLOADED,
    AI_ANALYSIS_COMPLETED,
    REQUIREMENT_ADDED,
    REQUIREMENT_VERIFIED,
    MARKETPLACE_LISTING_PUBLISHED,
    DISTRIBUTOR_VERIFIED,
    DISTRIBUTOR_REJECTED
}
